import {
  getUserDetail,
  getPlayersData,
  getSelectionInfo,
  getBatsmenData,
  getBowlerData,
  getSearchableTeamsInfo,
  getSearchablePlayersInfo,
  getChooseCricketClips,
  getClipsInfo,
  getPublishedReelDetails,
  addClipComment,
  addRating,
  getStandardHighlights,
  getMostViewedHighlights,
  getTopRatedHighlights,
} from './userActions';

export default {
  getUserDetail,
  getPlayersData,
  getSelectionInfo,
  getBatsmenData,
  getBowlerData,
  getSearchableTeamsInfo,
  getSearchablePlayersInfo,
  getChooseCricketClips,
  getClipsInfo,
  getPublishedReelDetails,
  addClipComment,
  addRating,
  getStandardHighlights,
  getMostViewedHighlights,
  getTopRatedHighlights,
};
